create table chat_history
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp default CURRENT_TIMESTAMP not null
);

alter table chat_history
    owner to postgres;

create table chat_completion_requests
(
    id              bigint generated by default as identity
        primary key,
    ai_model        varchar(255),
    chat_history_id bigint not null
        constraint fk_chat_history
            references chat_history
            on delete cascade
);

alter table chat_completion_requests
    owner to postgres;

create table flyway_schema_history
(
    installed_rank integer                 not null
        constraint flyway_schema_history_pk
            primary key,
    version        varchar(50),
    description    varchar(200)            not null,
    type           varchar(20)             not null,
    script         varchar(1000)           not null,
    checksum       integer,
    installed_by   varchar(100)            not null,
    installed_on   timestamp default now() not null,
    execution_time integer                 not null,
    success        boolean                 not null
);

alter table flyway_schema_history
    owner to postgres;

create index flyway_schema_history_s_idx
    on flyway_schema_history (success);

create table user_messages
(
    message_id                 bigint generated by default as identity
        constraint gpt_messages_pkey
            primary key,
    message_content            text not null,
    chat_history_id            bigint
        constraint fk9t7gcn9yiwmohoyilti5k5cpt
            references chat_history,
    chat_completion_request_id bigint
        constraint fk4jlta1jlnjj471l6ghscu1u3m
            references chat_completion_requests,
    role                       varchar(255)
);

alter table user_messages
    owner to postgres;

create table transcription_requests
(
    id                 bigint generated by default as identity
        primary key,
    user_id            bigint       not null,
    chat_history_id    bigint
        references chat_history
            on delete cascade,
    audio_file_path    varchar(255) not null,
    ai_model           varchar(255) not null,
    transcription_text text,
    message_id         bigint
        references user_messages,
    created_at         timestamp default CURRENT_TIMESTAMP,
    audio_file         bytea,
    user_message_id    bigint
        constraint fkp8dw5g0v6qjo2g9pw1cpqd71
            references user_messages
);

alter table transcription_requests
    owner to postgres;

create table chat_completion_responses
(
    id                         bigint generated by default as identity
        primary key,
    message_content            varchar(255),
    chat_completion_request_id bigint not null
        constraint fk1s3quy7618a9wmp7iltypn4y4
            references chat_completion_requests
);

alter table chat_completion_responses
    owner to postgres;

create table choices
(
    id                          bigint generated by default as identity
        primary key,
    user_message_id             bigint not null,
    chat_completion_response_id bigint not null
        constraint fk7bup4wtxvv7x5hd3q201hp1dk
            references chat_completion_responses,
    gpt_message_id              bigint not null
        constraint uk5sq03eqx55hm1kf2rdemfd1m2
            unique
        constraint fkrmn3g1oavvj0ktsyw31fcuqe4
            references user_messages
);

alter table choices
    owner to postgres;

